modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = ""
license = "MIT License"

[[mods]]
    modId = "sticks_and_stones"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:brown_mushroom"
    authors = "DavigJ"
    credits = "DavigJ"
    displayName = "Sticks and Stones"
    description = '''
    Break my bones.
    '''

[[dependencies.template_mod]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.template_mod]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.template_mod]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.1.1,)"
    ordering = "AFTER"
    side = "BOTH"